# Site settings
title: Rabiul Awal
SEOTitle: Rabiul Awal
header-img: ""
email: rabiul.awal@mila.quebec
description: ""
keyword: "rabiul awal, nlp, deep learning, bangladesh"
url: "https://rabiul.me"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username:    rabiulcste
twitter_username:   _rabiulawal
linkedin_username:  rabiulawal
resume_link: true


# Pagination
pagination:
  enabled: true

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
#paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins:
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-twitter-plugin
  - jemoji



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: rabiul-me

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: rabiul.me



scholar:
    first_name: Md Rabiul
    last_name: Awal
    source: /_bibliography/
    style: _csl/transactions-on-algorithms.csl
    ignore: ['url', 'doi']
    bibliography: references.bib
    bibliography_template: bibtemplate
    bibtex_filters: [latex, smallcaps, superscript]
    replace_strings: true
    query: "@*"


# Sidebar settings
sidebar: false                           # whether or not using Sidebar.
sidebar-about-description: "2nd year CS masters student at UofS with research focus on language+vision and deep learning. 
Worked as a software engineer for 2 years at Goava, building data-driven b2b sales intelligence products. 
<br><br> My key skills are Python, Pytorch, NoSQL, AWS and ElasticSearch."
sidebar-avatar: https://github.com/rabiulcste.png # use absolute URL, seeing it's used in both `/` and `/about/`
sidebar-name: Rabiul Awal
sidebar-email: "Email: rabiul.awal @ mila.quebec"



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 4              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false